/**
 * Copyright 2015 David T. Sadler
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
'use strict';

var constants = {
    CHANGE_APP_ID: 'CHANGE_APP_ID',
    CHANGE_ENVIRONMENT: 'CHANGE_ENVIRONMENT',
    CHANGE_VERSION: 'CHANGE_VERSION',
    CHANGE_SITE: 'CHANGE_SITE',
    CHANGE_RESPONSE_FORMAT: 'CHANGE_RESPONSE_FORMAT',
    ADD_ASPECT_FILTER: 'ADD_ASPECT_FILTER',
    REMOVE_ASPECT_FILTER: 'REMOVE_ASPECT_FILTER',
    CHANGE_ASPECT_NAME: 'CHANGE_ASPECT_NAME',
    ADD_ASPECT_VALUE_NAME: 'ADD_ASPECT_VALUE_NAME',
    REMOVE_ASPECT_VALUE_NAME: 'REMOVE_ASPECT_VALUE_NAME',
    CHANGE_ASPECT_VALUE_NAME: 'CHANGE_ASPECT_VALUE_NAME',
    ADD_CATEGORY_ID: 'ADD_CATEGORY_ID',
    REMOVE_CATEGORY_ID: 'REMOVE_CATEGORY_ID',
    CHANGE_CATEGORY_ID: 'CHANGE_CATEGORY_ID',
    CHANGE_DESCRIPTION_SEARCH: 'CHANGE_DESCRIPTION_SEARCH',
    ADD_ITEM_FILTER: 'ADD_ITEM_FILTER',
    REMOVE_ITEM_FILTER: 'REMOVE_ITEM_FILTER',
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_PARAM_NAME: 'CHANGE_PARAM_NAME',
    CHANGE_PARAM_VALUE: 'CHANGE_PARAM_VALUE',
    ADD_VALUE: 'ADD_VALUE',
    REMOVE_VALUE: 'REMOVE_VALUE',
    CHANGE_VALUE: 'CHANGE_VALUE',
    CHANGE_KEYWORDS: 'CHANGE_KEYWORDS',
    ADD_OUTPUT_SELECTOR: 'ADD_OUTPUT_SELECTOR',
    REMOVE_OUTPUT_SELECTOR: 'REMOVE_OUTPUT_SELECTOR',
    CHANGE_OUTPUT_SELECTOR: 'CHANGE_OUTPUT_SELECTOR',
    CHANGE_CUSTOM_ID: 'CHANGE_CUSTOM_ID',
    CHANGE_GEO_TARGETING: 'CHANGE_GEO_TARGETING',
    CHANGE_NETWORK_ID: 'CHANGE_NETWORK_ID',
    CHANGE_TRACKING_ID: 'CHANGE_TRACKING_ID',
    CHANGE_BUYER_POSTAL_CODE: 'CHANGE_BUYER_POSTAL_CODE',
    CHANGE_ENTRIES_PER_PAGE: 'CHANGE_ENTRIES_PER_PAGE',
    CHANGE_PAGE_NUMBER: 'CHANGE_PAGE_NUMBER',
    CHANGE_SORT_ORDER: 'CHANGE_SORT_ORDER'
};

module.exports = constants;
