# ***************************
# SITE
# ***************************

# Can be overridden in other config files to switch off code such as Google Analytics.
production: true

# Full url for the site minus the ending forward slash.
url: http://devbay.net

# Appears in the <title> and <header> elements within the site and the RSS feed.
name: Devbay

# Used in various places where the author of the site needs to appear.
author: David T. Sadler

author_twitter: davidtsadler

author_gravatar: bbf9fb140f0e3d23b65c88d5b3baa3a2

# Used in the meta description tag of the site and the description element of the RSS feed.
description: Use the eBay API in your PHP projects with this SDK.

# Twitter name minus the @ character.
twitter: devbaydotnet

google_group: ebay-sdk-php

# Git hub name.
github: davidtsadler/devbay.net

# Google plus profile ID
google_plus_id: 103985843031062200565

# Used in the footer of the site.
copyright_year: 2014

# Optional Disqus integration.
disqus_shortname: devbay

# ***************************
# JEKYLL
# ***************************

# Directory where Jekyll will look to transform files.
source: site

# Directory where Jekyll will save transformed files.
destination: .tmp/site

# Markdown engine that will be used.
markdown: redcarpet

redcarpet:
  extensions: ['tables']

highlighter: true

# Format that Jekyll will use when generating URLs to posts.
permalink: /blog/:year/:month/:day/:title/

# ***************************
# PLUGINS
# ***************************

rss_path: blog

rss_post_limit: 20
