# ***************************
# SITE
# ***************************

# Appears in the <title> and <header> elements within the site.
title: Devbay

# Used in various places where the author of the site needs to appear. 
author: David T. Sadler

author_twitter: davidtsadler

# Used in the meta description tag of the site and the description element of the RSS feed.
description: 

# Twitter name minus the @ character. 
twitter: devbaydotnet

google_group: ebay-sdk-php

# Git hub name.
github: davidtsadler/devbay.net

# Google plus profile ID
google_plus_id: 103985843031062200565

# Used in the footer of the site.
copyright_year: 2014

# ***************************
# JEKYLL
# ***************************

# Directory where Jekyll will look to transform files.
source: site 

# Directory where Jekyll will save transformed files.
destination: .tmp/

# Markdown engine that will be used.
markdown: redcarpet

pygments: true
