#!/usr/bin/env bash

SITES=(0 2 3 15 16 23 71 77 100 101 123 146 186 193 201 203 205 207 210 211 212 216)

for i in "${SITES[@]}"
do
  saxonb-xslt										\
    -ext:on										\
    -s:.tmp/downloads/ebay-details/$i.xml						\
    -xsl:xsl/ebay_details.xsl								\
    siteID=$i										\
    destDirectory=site/developers/tools/ebay-details
done

exit 0
